[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/knative/pkg"
  # HEAD as of 2019-03-21
  revision = "60fdcbcabd2faeb34328d8b2725dc76c59189453"

[[constraint]]
  name = "github.com/knative/serving"
  # HEAD as of 2019-03-21
  revision = "99774a5af4c7b688998ed05ec2c1e1f4e97eef70"

[[constraint]]
  name = "github.com/knative/eventing"
  # HEAD as of 2019-03-21
  revision = "4d7c827969e5d30400d23b9687c0450079c2e11e"