[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.10"

[[constraint]]
  name = "knative.dev/eventing"
  version = "v0.10.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"


[[override]]
  name = "google.golang.org/genproto"
  revision = "e7d98fc518a78c9f8b5ee77be7b0b317475d89e1"

[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  # The build fails against 0.12.6 and newer because
  # stackdriver.Options.GetMonitoredResource was removed.
  version = "<=v0.12.5"

[[override]]
  name = "go.opencensus.io"
  # Needed because this includes the appropriate version of metricsdata
  version = "v0.22.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false