[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/knative/pkg"
  # HEAD as of 2019-03-21
  source = "github.com/n3wscott/pkg"
  revision = "d4b8b65b25fb5bc7e4782c8198d25ed5fc4203ea"

[[constraint]]
  name = "github.com/knative/serving"
  # HEAD as of 2019-03-21
  revision = "99774a5af4c7b688998ed05ec2c1e1f4e97eef70"

[[constraint]]
  name = "github.com/knative/eventing"
  # HEAD as of 2019-03-21
  revision = "4d7c827969e5d30400d23b9687c0450079c2e11e"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

# 0.1.9 is most recent version that still uses K8s 1.12. 0.1.10 uses K8s 1.13.
[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=0.1.9"
