[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.10"

[[constraint]]
  name = "knative.dev/eventing"
  version = "v0.10.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"
